### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by Z41N** [MapleMyth/ClientImageLoader#9]
Hey everyone,

Thank you for releasing this. 
Having an issue with compiling/linking - keeps saying detours.lib was created by different version, and to rebuild the objects and libraries but not sure what that means because I'm trying to build the solution and that's whats causing the error

**Comment by Z41N** [comment]
Fixed by installing VS2015, delete and recloning, and restarting project

**Comment by RaphaelWoude** [comment]
If you have VS2015 installed, use the SDK from that version to build with VS2019/VS2022 or any other version you want.
